apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault-app
  name: vault-app
spec:
  type: LoadBalancer
  ports:
    - port: 8200
      targetPort: {{.Values.CONTAINER_PORT}}
      protocol: TCP
  selector:
    app: vault